name: Update tags
on:
    push:
        branches: [master]
jobs:
    update-tags:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: git fetch --all --tags
            - name: Get project version
              uses: thebongy/version-check@v2
              with:
                file: Cargo.toml
                tagFormat: v${version}
              id: get_project_version
            - name: Create a new tag
              if: steps.get_project_version.outputs.releaseVersion != 'v0.0.0'
              uses: actions/github-script@v7
              with:
               script: |
                github.rest.git.createRef({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: 'refs/tags/${{steps.get_project_version.outputs.releaseVersion}}',
                    sha: context.sha
                })